services:
  - type: web
    name: agent
    env: node
    rootDir: server/agent
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: EXECUTOR_URL
        fromService:
          type: web
          name: executor
          property: url

  - type: web
    name: executor
    env: node
    rootDir: server/executor
    buildCommand: npm install
    startCommand: node index.js
